package com.project.ui.student;

import com.project.common.constants.MessageConstant;
import com.project.common.utils.Dialog;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import com.project.controller.ConsultationController;
import com.project.controller.ModuleFeedbackController;
import org.bouncycastle.tsp.TSPUtil;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

import java.util.List;
import java.util.Map;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Olaf
 */
public class StudentFeedbackGui extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentAssignmentGui
     */
    public StudentFeedbackGui() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);

        refresh();

    }

    private void refresh() {
        fillInComboBox();
    }
    
   private void fillInComboBox() {
       moduleFeedbackComboBox.removeAllItems();
       List<Map<String,String>> lists = ModuleFeedbackController.getAllAvailableFeedbackForStudent();
       if (lists.isEmpty()) {
           moduleFeedbackComboBox.addItem(MessageConstant.CONDITION_NO_MODULE_CAN_FEEDBACK);
           JField19.setText("Module ID");
           JField18.setText("Lecturer Name");
           jTextArea1.setText("Please Enter Your Feedback.");
       } else {
           for (Map<String,String> list : lists) {
               moduleFeedbackComboBox.addItem(list.get("moduleCode"));
           }
       }
       moduleFeedbackComboBox.setSelectedIndex(0);
   }

    private void refreshDetails() {
        if (moduleFeedbackComboBox.getSelectedItem() != null) {
            if (moduleFeedbackComboBox.getSelectedItem().equals(MessageConstant.CONDITION_NO_MODULE_CAN_FEEDBACK)) {
                JField19.setText("Module ID");
                JField18.setText("Lecturer Name");
                jTextArea1.setText("Please Enter Your Feedback.");
            } else {
                Map<String,String> map = ModuleFeedbackController.getProjectModuleByCode((String) moduleFeedbackComboBox.getSelectedItem());
                    JField19.setText(map.get("moduleId"));
                    JField18.setText(map.get("lecturerName"));
                    jTextArea1.setText("Please Enter Your Feedback.");
            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuBtn33 = new javax.swing.JLabel();
        menuBtn34 = new javax.swing.JLabel();
        JField18 = new javax.swing.JTextField();
        menuBtn32 = new javax.swing.JLabel();
        menuBtn37 = new javax.swing.JLabel();
        moduleFeedbackComboBox = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        JSeparator37 = new javax.swing.JSeparator();
        JField19 = new javax.swing.JTextField();
        menuBtn36 = new javax.swing.JLabel();
        menuBtn30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBtn33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/quantity-24x24.png"))); // NOI18N
        menuBtn33.setText("MODULE ID");
        menuBtn33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn33.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn33.setOpaque(true);
        jPanel1.add(menuBtn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 40));

        menuBtn34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-24x24.png"))); // NOI18N
        menuBtn34.setText("LECTURER NAME");
        menuBtn34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn34.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn34.setOpaque(true);
        jPanel1.add(menuBtn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 300, 40));

        JField18.setEditable(false);
        JField18.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField18.setText("Lecturer Name");
        JField18.setBackground(new java.awt.Color(255, 255, 255));
        JField18.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        JField18.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField18.setForeground(new java.awt.Color(1, 1, 1));
        JField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JField18MouseClicked(evt);
            }
        });
        JField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JField18ActionPerformed(evt);
            }
        });
        jPanel1.add(JField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 35));

        menuBtn32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/quantity-24x24.png"))); // NOI18N
        menuBtn32.setText("MODULE");
        menuBtn32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn32.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn32.setOpaque(true);
        jPanel1.add(menuBtn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 300, 40));

        menuBtn37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/action-24x24.png"))); // NOI18N
        menuBtn37.setText("ACTION :");
        menuBtn37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn37.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn37.setOpaque(true);
        jPanel1.add(menuBtn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 90, 40));

        moduleFeedbackComboBox.setBackground(new java.awt.Color(254, 254, 254));
        moduleFeedbackComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moduleFeedbackComboBox.setFocusable(false);
        moduleFeedbackComboBox.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 12)); // NOI18N
        moduleFeedbackComboBox.setToolTipText("d");
        moduleFeedbackComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleFeedbackComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(moduleFeedbackComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, 35));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-green-24x24.png"))); // NOI18N
        jLabel40.setText("SUBMIT");
        jLabel40.setBackground(new java.awt.Color(254, 254, 254));
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 1, 1));
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel40.setOpaque(true);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, 170, 35));

        JSeparator37.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(JSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 170, 10));

        JField19.setEditable(false);
        JField19.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField19.setText("Module Id");
        JField19.setBackground(new java.awt.Color(255, 255, 255));
        JField19.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        JField19.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField19.setForeground(new java.awt.Color(1, 1, 1));
        JField19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JField19MouseClicked(evt);
            }
        });
        jPanel1.add(JField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 35));

        menuBtn36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/summary-24.png"))); // NOI18N
        menuBtn36.setText("COMMENT");
        menuBtn36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn36.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn36.setOpaque(true);
        jPanel1.add(menuBtn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, 40));

        menuBtn30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bill-24x24.png"))); // NOI18N
        menuBtn30.setText("MODULE FEEDBACK");
        menuBtn30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn30.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn30.setOpaque(true);
        jPanel1.add(menuBtn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 500, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Please Enter Your Feedback.");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 310, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JField18MouseClicked

    private void moduleFeedbackComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleFeedbackComboBoxActionPerformed
        refreshDetails();
    }//GEN-LAST:event_moduleFeedbackComboBoxActionPerformed

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
       if (moduleFeedbackComboBox.getSelectedItem().equals(MessageConstant.CONDITION_NO_MODULE_CAN_FEEDBACK)) {
           Dialog.ErrorDialog(MessageConstant.ERROR_SELECTION_EMPTY);
           return;
       }

       if (jTextArea1.getText().equals("Please Enter Your Feedback.")) {
           Dialog.ErrorDialog("Please Enter Your Feedback.");
           return;
       }

       if (ModuleFeedbackController.submitModuleFeedback(Integer.valueOf(JField19.getText()), jTextArea1.getText())) {
            refresh();
       }

    }//GEN-LAST:event_jLabel40MouseClicked

    private void JField19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JField19MouseClicked

    private void JField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JField18ActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        if(jTextArea1.getText().equals("Please Enter Your Feedback.")) {
            jTextArea1.setText("");
        }
    }//GEN-LAST:event_jTextArea1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JField18;
    private javax.swing.JTextField JField19;
    private javax.swing.JSeparator JSeparator37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel menuBtn30;
    private javax.swing.JLabel menuBtn32;
    private javax.swing.JLabel menuBtn33;
    private javax.swing.JLabel menuBtn34;
    private javax.swing.JLabel menuBtn36;
    private javax.swing.JLabel menuBtn37;
    private static javax.swing.JComboBox<String> moduleFeedbackComboBox;
    // End of variables declaration//GEN-END:variables
}
