/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.project.ui.administrator;

import com.project.common.utils.DateTimeUtils;
import com.project.common.utils.Dialog;
import com.project.common.utils.JsonHandler;
import com.project.controller.IntakesController;
import com.project.controller.UserAccountController;
import org.json.simple.JSONObject;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Dell Technologies
 */
public class intakeManagement extends javax.swing.JInternalFrame {
    String newIntakeCode;
    LocalDate intakeStartDate, intakeEndDate;
    JsonHandler assignedModules;

    /**
     * Creates new form intakeManagement
     */
    public intakeManagement() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        initForm();
    }
    
    private void initForm() {
        intakeCode.setEnabled(false);
        datePicker1.setEnabled(false);
        datePicker2.setEnabled(false);
        backBtn1.setEnabled(false);
        backBtn2.setEnabled(false);
        nextBtn2.setEnabled(false);
        saveBtn.setEnabled(false);

        JsonHandler PMs = UserAccountController.getPMs();
        for (int i = 0; i < PMs.getAll().size(); i++) {
            String projectManager = PMs.getObject(i).get("first_name") + " " + PMs.getObject(i).get("last_name") + "-" + PMs.getObject(i).get("id");
            PM1.addItem(projectManager);
            PM2.addItem(projectManager);
            PM3.addItem(projectManager);
            PM4.addItem(projectManager);

        }

        jPanel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        module3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        PM3 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        module1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        PM1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        module4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        PM4 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        module2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        PM2 = new javax.swing.JComboBox<>();
        nextBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        intakeCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        nextBtn2 = new javax.swing.JButton();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        backBtn1 = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        endDatePre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        intakeCodePre = new javax.swing.JLabel();
        module1PMPre = new javax.swing.JLabel();
        module2PMPre = new javax.swing.JLabel();
        module3PMPre = new javax.swing.JLabel();
        module4PMPre = new javax.swing.JLabel();
        startDatePre = new javax.swing.JLabel();
        module1Pre = new javax.swing.JLabel();
        module2Pre = new javax.swing.JLabel();
        module3Pre = new javax.swing.JLabel();
        module4Pre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1093, 695));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-properties-24.png"))); // NOI18N
        jLabel5.setText("NEW MODULES");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 35));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bill-24x24.png"))); // NOI18N
        jLabel10.setText("Module 3");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/officer-24x24.png"))); // NOI18N
        jLabel6.setText("Project Manager :");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 35));

        module3.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        module3.setForeground(new java.awt.Color(1, 1, 1));
        module3.setBorder(null);
        module3.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        module3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                module3KeyReleased(evt);
            }
        });
        jPanel5.add(module3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 35));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-24.png"))); // NOI18N
        jLabel12.setText("Module Name :");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setOpaque(true);
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 35));

        PM3.setBackground(new java.awt.Color(254, 254, 254));
        PM3.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 12)); // NOI18N
        PM3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Project Managers --" }));
        PM3.setToolTipText("Select Project Manager");
        PM3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PM3.setFocusable(false);
        jPanel5.add(PM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 35));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 440, 240));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bill-24x24.png"))); // NOI18N
        jLabel13.setText("Module 1");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/officer-24x24.png"))); // NOI18N
        jLabel14.setText("Project Manager :");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setOpaque(true);
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 35));

        module1.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        module1.setForeground(new java.awt.Color(1, 1, 1));
        module1.setBorder(null);
        module1.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        module1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                module1KeyReleased(evt);
            }
        });
        jPanel6.add(module1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 35));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-24.png"))); // NOI18N
        jLabel15.setText("Module Name :");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 35));

        PM1.setBackground(new java.awt.Color(254, 254, 254));
        PM1.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 12)); // NOI18N
        PM1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Project Managers --" }));
        PM1.setToolTipText("Select Project Manager");
        PM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PM1.setFocusable(false);
        jPanel6.add(PM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 35));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 440, 240));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bill-24x24.png"))); // NOI18N
        jLabel16.setText("Module 4");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/officer-24x24.png"))); // NOI18N
        jLabel17.setText("Project Manager :");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setOpaque(true);
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 35));

        module4.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        module4.setForeground(new java.awt.Color(1, 1, 1));
        module4.setBorder(null);
        module4.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        module4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                module4KeyReleased(evt);
            }
        });
        jPanel7.add(module4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 35));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-24.png"))); // NOI18N
        jLabel18.setText("Module Name :");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.setOpaque(true);
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 35));

        PM4.setBackground(new java.awt.Color(254, 254, 254));
        PM4.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 12)); // NOI18N
        PM4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Project Managers --" }));
        PM4.setToolTipText("Select Project Manager");
        PM4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PM4.setFocusable(false);
        jPanel7.add(PM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 35));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 440, 240));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bill-24x24.png"))); // NOI18N
        jLabel19.setText("Module 2");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/officer-24x24.png"))); // NOI18N
        jLabel20.setText("Project Manager :");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setOpaque(true);
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 35));

        module2.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        module2.setForeground(new java.awt.Color(1, 1, 1));
        module2.setBorder(null);
        module2.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        module2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                module2KeyReleased(evt);
            }
        });
        jPanel8.add(module2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 35));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-24.png"))); // NOI18N
        jLabel21.setText("Module Name :");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setOpaque(true);
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 35));

        PM2.setBackground(new java.awt.Color(254, 254, 254));
        PM2.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 12)); // NOI18N
        PM2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Project Managers --" }));
        PM2.setToolTipText("Select Project Manager");
        PM2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PM2.setFocusable(false);
        jPanel8.add(PM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 35));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 440, 240));

        nextBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/forward-button-24.png"))); // NOI18N
        nextBtn1.setText("Next");
        nextBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        nextBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBtn1MouseClicked(evt);
            }
        });
        jPanel2.add(nextBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 110, 40));

        jTabbedPane1.addTab("Modules", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        intakeCode.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        intakeCode.setBorder(null);
        intakeCode.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        intakeCode.setForeground(new java.awt.Color(1, 1, 1));
        intakeCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                intakeCodeKeyReleased(evt);
            }
        });
        jPanel3.add(intakeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 290, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/summary-24.png"))); // NOI18N
        jLabel1.setText("SUMMARY");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 290, 35));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 10, 630));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel2.setText("Start Date :");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 100, 35));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel3.setText(" End Date :");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 35));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-24.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });
        jPanel3.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 110, 40));

        nextBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/forward-button-24.png"))); // NOI18N
        nextBtn2.setText("Next");
        nextBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        nextBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBtn2MouseClicked(evt);
            }
        });
        jPanel3.add(nextBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 110, 40));
        jPanel3.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 290, 35));
        jPanel3.add(datePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 290, 35));

        backBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back-arrow-24.png"))); // NOI18N
        backBtn1.setText("Back");
        backBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtn1MouseClicked(evt);
            }
        });
        jPanel3.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 110, 40));

        backBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back-arrow-24.png"))); // NOI18N
        backBtn2.setText("Back");
        backBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtn2MouseClicked(evt);
            }
        });
        jPanel3.add(backBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 110, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/new-copy-24.png"))); // NOI18N
        jLabel7.setText("NEW INTAKE");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 35));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("End Date :");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 100, 35));

        endDatePre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endDatePre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        endDatePre.setOpaque(true);
        jPanel4.add(endDatePre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 340, 35));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Module 1 :");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setOpaque(true);
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 35));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Module 2 :");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setOpaque(true);
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 35));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Module 3 :");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.setOpaque(true);
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 35));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Module 4 :");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setOpaque(true);
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 35));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Start Date :");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.setOpaque(true);
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, 35));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Intake Code :");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.setOpaque(true);
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 35));

        intakeCodePre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intakeCodePre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intakeCodePre.setOpaque(true);
        jPanel4.add(intakeCodePre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 340, 35));

        module1PMPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module1PMPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module1PMPre.setOpaque(true);
        jPanel4.add(module1PMPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 340, 35));

        module2PMPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module2PMPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module2PMPre.setOpaque(true);
        jPanel4.add(module2PMPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 340, 35));

        module3PMPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module3PMPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module3PMPre.setOpaque(true);
        jPanel4.add(module3PMPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 340, 35));

        module4PMPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module4PMPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module4PMPre.setOpaque(true);
        jPanel4.add(module4PMPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 340, 35));

        startDatePre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startDatePre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startDatePre.setOpaque(true);
        jPanel4.add(startDatePre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 340, 35));

        module1Pre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module1Pre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module1Pre.setOpaque(true);
        jPanel4.add(module1Pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 340, 35));

        module2Pre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module2Pre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module2Pre.setOpaque(true);
        jPanel4.add(module2Pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 340, 35));

        module3Pre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module3Pre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module3Pre.setOpaque(true);
        jPanel4.add(module3Pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 340, 35));

        module4Pre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        module4Pre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        module4Pre.setOpaque(true);
        jPanel4.add(module4Pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 340, 35));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 490, 480));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Intake Code :");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 35));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 630));

        jTabbedPane1.addTab("Intakes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtn2MouseClicked
        String newIntakeCode = intakeCode.getText();
        LocalDate startDate = datePicker2.getDate();
        LocalDate endDate = datePicker1.getDate();

        if (newIntakeCode.isEmpty() || startDate == null || endDate == null) {
            Dialog.ErrorDialog("No empty fields are allowed!");
        } else {
            if (IntakesController.validateNewIntakeCode(newIntakeCode) && ChronoUnit.YEARS.between(startDate, endDate) >= 1) {
                this.newIntakeCode = newIntakeCode;
                this.intakeStartDate = startDate;
                this.intakeEndDate = endDate;

                // display preview
                intakeCodePre.setText(newIntakeCode);
                module1Pre.setText(assignedModules.getObject(0).get("moduleCode").toString());
                module1PMPre.setText(assignedModules.getObject(0).get("projectManagerName").toString());
                module2Pre.setText(assignedModules.getObject(1).get("moduleCode").toString());
                module2PMPre.setText(assignedModules.getObject(1).get("projectManagerName").toString());
                module3Pre.setText(assignedModules.getObject(2).get("moduleCode").toString());
                module3PMPre.setText(assignedModules.getObject(2).get("projectManagerName").toString());
                module4Pre.setText(assignedModules.getObject(3).get("moduleCode").toString());
                module4PMPre.setText(assignedModules.getObject(3).get("projectManagerName").toString());
                startDatePre.setText(DateTimeUtils.formatStrDate(startDate));
                endDatePre.setText(DateTimeUtils.formatStrDate(endDate));

                intakeCode.setEnabled(false);
                datePicker1.setEnabled(false);
                datePicker2.setEnabled(false);
                backBtn1.setEnabled(false);
                nextBtn2.setEnabled(false);
                saveBtn.setEnabled(true);
                backBtn2.setEnabled(true);

                jPanel4.setVisible(true);
            } else if (!IntakesController.validateNewIntakeCode(newIntakeCode)) {
                Dialog.ErrorDialog("\"" + newIntakeCode + "\"" + " already exists!");
            } else {
                Dialog.ErrorDialog("The period between start date and end date must be at least 1 year");
            }

        }
    }//GEN-LAST:event_nextBtn2MouseClicked

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        IntakesController.registerNewIntake(newIntakeCode, intakeStartDate, intakeEndDate, assignedModules);
    }//GEN-LAST:event_saveBtnMouseClicked

    private void intakeCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intakeCodeKeyReleased
        intakeCode.setText(intakeCode.getText().toUpperCase());
    }//GEN-LAST:event_intakeCodeKeyReleased

    private void backBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtn1MouseClicked
        jTabbedPane1.setSelectedIndex(0);
        intakeCode.setText(null);
        intakeCode.setEnabled(false);
        datePicker1.setDate(null);
        datePicker1.setEnabled(false);
        datePicker2.setDate(null);
        datePicker2.setEnabled(false);
        backBtn1.setEnabled(false);
        nextBtn2.setEnabled(false);
    }//GEN-LAST:event_backBtn1MouseClicked

    private void module3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_module3KeyReleased
        module3.setText(module3.getText().toUpperCase());
    }//GEN-LAST:event_module3KeyReleased

    private void module1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_module1KeyReleased
        module1.setText(module1.getText().toUpperCase());
    }//GEN-LAST:event_module1KeyReleased

    private void module4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_module4KeyReleased
        module4.setText(module4.getText().toUpperCase());
    }//GEN-LAST:event_module4KeyReleased

    private void module2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_module2KeyReleased
        module2.setText(module2.getText().toUpperCase());
    }//GEN-LAST:event_module2KeyReleased

    private void nextBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtn1MouseClicked
        jPanel4.setVisible(false);
        backBtn2.setEnabled(false);
        saveBtn.setEnabled(false);

        if (!module1.getText().isEmpty() && !module2.getText().isEmpty() && !module3.getText().isEmpty() && !module4.getText().isEmpty() && !PM1.getSelectedItem().equals("-- Project Managers --") && !PM2.getSelectedItem().equals("-- Project Managers --") && !PM3.getSelectedItem().equals("-- Project Managers --") && !PM4.getSelectedItem().equals("-- Project Managers --")) {
            assignedModules = new JsonHandler();

            JSONObject moduleObj1 = new JSONObject();
            moduleObj1.put("moduleCode", module1.getText());
            moduleObj1.put("projectManager", Integer.parseInt(PM1.getSelectedItem().toString().split("-")[1]));
            moduleObj1.put("projectManagerName", PM1.getSelectedItem().toString().split("-")[0]);
            assignedModules.addObject(moduleObj1);

            JSONObject moduleObj2 = new JSONObject();
            moduleObj2.put("moduleCode", module2.getText());
            moduleObj2.put("projectManager", Integer.parseInt(PM2.getSelectedItem().toString().split("-")[1]));
            moduleObj2.put("projectManagerName", PM2.getSelectedItem().toString().split("-")[0]);
            assignedModules.addObject(moduleObj2);

            JSONObject moduleObj3 = new JSONObject();
            moduleObj3.put("moduleCode", module3.getText());
            moduleObj3.put("projectManager", Integer.parseInt(PM3.getSelectedItem().toString().split("-")[1]));
            moduleObj3.put("projectManagerName", PM3.getSelectedItem().toString().split("-")[0]);
            assignedModules.addObject(moduleObj3);

            JSONObject moduleObj4 = new JSONObject();
            moduleObj4.put("moduleCode", module4.getText());
            moduleObj4.put("projectManager", Integer.parseInt(PM4.getSelectedItem().toString().split("-")[1]));
            moduleObj4.put("projectManagerName", PM4.getSelectedItem().toString().split("-")[0]);
            assignedModules.addObject(moduleObj4);

            jTabbedPane1.setSelectedIndex(1);
            intakeCode.setText(null);
            intakeCode.setEnabled(true);
            datePicker1.setDate(null);
            datePicker1.setEnabled(true);
            datePicker2.setDate(null);
            datePicker2.setEnabled(true);
            backBtn1.setEnabled(true);
            nextBtn2.setEnabled(true);
        } else if (module1.getText().isEmpty() || module2.getText().isEmpty() || module3.getText().isEmpty() || module4.getText().isEmpty()) {
            Dialog.ErrorDialog("All modules are required!");
        } else {
            Dialog.ErrorDialog("Each module must have an assigned Project Manager!");
        }

    }//GEN-LAST:event_nextBtn1MouseClicked

    private void backBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtn2MouseClicked
        jPanel4.setVisible(false);
        intakeCode.setEnabled(true);
        datePicker1.setEnabled(true);
        datePicker2.setEnabled(true);
        nextBtn2.setEnabled(true);
        backBtn1.setEnabled(true);
        backBtn2.setEnabled(false);
        saveBtn.setEnabled(false);
    }//GEN-LAST:event_backBtn2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> PM1;
    private static javax.swing.JComboBox<String> PM2;
    private static javax.swing.JComboBox<String> PM3;
    private static javax.swing.JComboBox<String> PM4;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn2;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JLabel endDatePre;
    private javax.swing.JTextField intakeCode;
    private javax.swing.JLabel intakeCodePre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField module1;
    private javax.swing.JLabel module1PMPre;
    private javax.swing.JLabel module1Pre;
    private javax.swing.JTextField module2;
    private javax.swing.JLabel module2PMPre;
    private javax.swing.JLabel module2Pre;
    private javax.swing.JTextField module3;
    private javax.swing.JLabel module3PMPre;
    private javax.swing.JLabel module3Pre;
    private javax.swing.JTextField module4;
    private javax.swing.JLabel module4PMPre;
    private javax.swing.JLabel module4Pre;
    private javax.swing.JButton nextBtn1;
    private javax.swing.JButton nextBtn2;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel startDatePre;
    // End of variables declaration//GEN-END:variables
}
