/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.project.ui.authentication;

import com.project.common.constants.UserRoleType;
import com.project.common.utils.DateTimeUtils;
import com.project.controller.authentication.UserAccountController;
import static com.project.controller.authentication.UserAccountController.updateUserProfileById;
import static com.project.controller.authentication.UserAccountController.changePasswordById;
import static com.project.controller.authentication.UserAccountController.changeSecurityPhraseById;
import com.project.pojo.UserAccount;
import com.project.pojo.UserAuthentication;
import java.time.LocalDateTime;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Olaf
 */
public class UserProfileGui extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form UserProfileGui
     */
    public UserProfileGui() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);        
        // UserProfilePanel.setText(PropertiesReader.getProperty("UserProfilePanel"));
        fillInUserDetials();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPanel = new javax.swing.JTabbedPane();
        Panel1 = new javax.swing.JPanel();
        JField28 = new javax.swing.JTextField();
        JField29 = new javax.swing.JTextField();
        JField30 = new javax.swing.JTextField();
        JField31 = new javax.swing.JTextField();
        JField34 = new javax.swing.JTextField();
        JField36 = new javax.swing.JTextField();
        menuBtn18 = new javax.swing.JLabel();
        menuBtn19 = new javax.swing.JLabel();
        JLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        JSeparator25 = new javax.swing.JSeparator();
        JSeparator26 = new javax.swing.JSeparator();
        JSeparator27 = new javax.swing.JSeparator();
        JSeparator28 = new javax.swing.JSeparator();
        JSeparator30 = new javax.swing.JSeparator();
        JSeparator33 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        JField39 = new javax.swing.JTextField();
        JField40 = new javax.swing.JTextField();
        JField42 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        JSeparator34 = new javax.swing.JSeparator();
        JSeparator35 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        JField41 = new javax.swing.JTextField();
        JSeparator36 = new javax.swing.JSeparator();
        UserProfilePanel = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        JField37 = new javax.swing.JTextField();
        JField43 = new javax.swing.JTextField();
        menuBtn20 = new javax.swing.JLabel();
        menuBtn21 = new javax.swing.JLabel();
        JLabel14 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        JSeparator37 = new javax.swing.JSeparator();
        JSeparator39 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        JField44 = new javax.swing.JTextField();
        JField45 = new javax.swing.JTextField();
        JField46 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        JSeparator40 = new javax.swing.JSeparator();
        JSeparator41 = new javax.swing.JSeparator();
        UserProfilePanel1 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        JField48 = new javax.swing.JTextField();
        JSeparator43 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        JField49 = new javax.swing.JTextField();
        JSeparator44 = new javax.swing.JSeparator();
        Panel3 = new javax.swing.JPanel();
        JField38 = new javax.swing.JTextField();
        JField47 = new javax.swing.JTextField();
        menuBtn22 = new javax.swing.JLabel();
        menuBtn23 = new javax.swing.JLabel();
        JLabel15 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        JSeparator38 = new javax.swing.JSeparator();
        JSeparator42 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        JField50 = new javax.swing.JTextField();
        JField51 = new javax.swing.JTextField();
        JField52 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        JSeparator45 = new javax.swing.JSeparator();
        JSeparator46 = new javax.swing.JSeparator();
        UserProfilePanel2 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        JField53 = new javax.swing.JTextField();
        JSeparator47 = new javax.swing.JSeparator();
        jLabel64 = new javax.swing.JLabel();
        JField54 = new javax.swing.JTextField();
        JSeparator48 = new javax.swing.JSeparator();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainTabbedPanel.setBackground(new java.awt.Color(230, 230, 230));
        MainTabbedPanel.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N

        Panel1.setPreferredSize(new java.awt.Dimension(1050, 570));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JField28.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField28.setForeground(new java.awt.Color(1, 1, 1));
        JField28.setText("Username");
        JField28.setBorder(null);
        JField28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField28.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel1.add(JField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 35));

        JField29.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField29.setForeground(new java.awt.Color(1, 1, 1));
        JField29.setText("First Name");
        JField29.setBorder(null);
        JField29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField29.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel1.add(JField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 35));

        JField30.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField30.setForeground(new java.awt.Color(1, 1, 1));
        JField30.setText("Last Name");
        JField30.setBorder(null);
        JField30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField30.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel1.add(JField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 300, 35));

        JField31.setEditable(false);
        JField31.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField31.setForeground(new java.awt.Color(1, 1, 1));
        JField31.setText("Password");
        JField31.setBorder(null);
        JField31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField31.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField31.setEnabled(false);
        Panel1.add(JField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 300, 35));

        JField34.setEditable(false);
        JField34.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField34.setForeground(new java.awt.Color(1, 1, 1));
        JField34.setText("Security Phrase");
        JField34.setBorder(null);
        JField34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField34.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField34.setEnabled(false);
        Panel1.add(JField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 300, 35));

        JField36.setBackground(new java.awt.Color(242, 242, 242));
        JField36.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField36.setForeground(new java.awt.Color(1, 1, 1));
        JField36.setText("User ID");
        JField36.setBorder(null);
        JField36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField36.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField36.setEnabled(false);
        Panel1.add(JField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 35));

        menuBtn18.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn18.setText("EDIT PROFILE");
        menuBtn18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn18.setOpaque(true);
        Panel1.add(menuBtn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 620, 40));

        menuBtn19.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn19.setText("ACCOUNT INFORMATION");
        menuBtn19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn19.setOpaque(true);
        Panel1.add(menuBtn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 360, 40));

        JLabel13.setBackground(new java.awt.Color(105, 105, 105));
        JLabel13.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        JLabel13.setForeground(new java.awt.Color(1, 1, 1));
        JLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-24x24.png"))); // NOI18N
        JLabel13.setText("USER ID");
        Panel1.add(JLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel32.setBackground(new java.awt.Color(105, 105, 105));
        jLabel32.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(1, 1, 1));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/name-24x24.png"))); // NOI18N
        jLabel32.setText("USERNAME");
        Panel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel33.setBackground(new java.awt.Color(105, 105, 105));
        jLabel33.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(1, 1, 1));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/name-24x24.png"))); // NOI18N
        jLabel33.setText("FIRST NAME");
        Panel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel34.setBackground(new java.awt.Color(105, 105, 105));
        jLabel34.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(1, 1, 1));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/name-24x24.png"))); // NOI18N
        jLabel34.setText("LAST NAME");
        Panel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel35.setBackground(new java.awt.Color(105, 105, 105));
        jLabel35.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(1, 1, 1));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel35.setText("PASSWORD");
        Panel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel37.setBackground(new java.awt.Color(105, 105, 105));
        jLabel37.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(1, 1, 1));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/security-24x24.png"))); // NOI18N
        jLabel37.setText("SECURITY PHRASE");
        Panel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel39.setBackground(new java.awt.Color(105, 105, 105));
        jLabel39.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(1, 1, 1));
        jLabel39.setText("ACTION");
        Panel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jLabel40.setBackground(new java.awt.Color(254, 254, 254));
        jLabel40.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(1, 1, 1));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-orange-24x24.png"))); // NOI18N
        jLabel40.setText("SAVE");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel40.setOpaque(true);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        Panel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 170, 35));

        jLabel41.setBackground(new java.awt.Color(254, 254, 254));
        jLabel41.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(1, 1, 1));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/status-24x24.png"))); // NOI18N
        jLabel41.setText("RESET");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel41.setOpaque(true);
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        Panel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 170, 35));

        JSeparator25.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, -1));

        JSeparator26.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, -1));

        JSeparator27.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, -1));

        JSeparator28.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 300, -1));

        JSeparator30.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, -1));

        JSeparator33.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, -1));

        jPanel9.setBackground(new java.awt.Color(254, 254, 254));

        jLabel44.setBackground(new java.awt.Color(105, 105, 105));
        jLabel44.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(1, 1, 1));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel44.setText("USER DATE CREATION");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel46.setBackground(new java.awt.Color(105, 105, 105));
        jLabel46.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(1, 1, 1));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel46.setText("USER LAST EDIT ON");
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JField39.setBackground(new java.awt.Color(254, 254, 254));
        JField39.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField39.setForeground(new java.awt.Color(1, 1, 1));
        JField39.setText("- LocalDateNow");
        JField39.setBorder(null);
        JField39.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField39.setEnabled(false);

        JField40.setBackground(new java.awt.Color(254, 254, 254));
        JField40.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField40.setForeground(new java.awt.Color(1, 1, 1));
        JField40.setText("- LocalDateNow");
        JField40.setBorder(null);
        JField40.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField40.setEnabled(false);

        JField42.setBackground(new java.awt.Color(254, 254, 254));
        JField42.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField42.setForeground(new java.awt.Color(1, 1, 1));
        JField42.setText("- LocalDateNow");
        JField42.setBorder(null);
        JField42.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField42.setEnabled(false);

        jLabel48.setBackground(new java.awt.Color(105, 105, 105));
        jLabel48.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(1, 1, 1));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel48.setText("USER ROLE");
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JField42, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JField40, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JField39, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel44)
                .addGap(0, 0, 0)
                .addComponent(JField39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46)
                .addGap(0, 0, 0)
                .addComponent(JField40, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel48)
                .addGap(0, 0, 0)
                .addComponent(JField42, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        Panel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 360, 390));

        JSeparator34.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 170, 10));

        JSeparator35.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 170, 10));

        jLabel47.setBackground(new java.awt.Color(105, 105, 105));
        jLabel47.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(1, 1, 1));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email-24x24.png"))); // NOI18N
        jLabel47.setText("EMAIL ADDRESS");
        Panel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        JField41.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField41.setForeground(new java.awt.Color(1, 1, 1));
        JField41.setText("Email Address");
        JField41.setBorder(null);
        JField41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField41.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel1.add(JField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 300, 35));

        JSeparator36.setForeground(new java.awt.Color(1, 1, 1));
        Panel1.add(JSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 300, -1));

        UserProfilePanel.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        UserProfilePanel.setForeground(new java.awt.Color(80, 80, 80));
        UserProfilePanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserProfilePanel.setText("UserProfilePanel @Version x.x Built On xx xx xxxx");
        UserProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel1.add(UserProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 628, 310, 30));

        MainTabbedPanel.addTab("Profile", Panel1);

        Panel2.setPreferredSize(new java.awt.Dimension(1050, 570));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JField37.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField37.setForeground(new java.awt.Color(1, 1, 1));
        JField37.setText("Please enter your old password");
        JField37.setBorder(null);
        JField37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField37.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel2.add(JField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 35));

        JField43.setBackground(new java.awt.Color(242, 242, 242));
        JField43.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField43.setForeground(new java.awt.Color(1, 1, 1));
        JField43.setText("User ID");
        JField43.setBorder(null);
        JField43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField43.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField43.setEnabled(false);
        Panel2.add(JField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 35));

        menuBtn20.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn20.setText("CHANGE PASSWORD");
        menuBtn20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn20.setOpaque(true);
        Panel2.add(menuBtn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 620, 40));

        menuBtn21.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn21.setText("ACCOUNT INFORMATION");
        menuBtn21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn21.setOpaque(true);
        Panel2.add(menuBtn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 360, 40));

        JLabel14.setBackground(new java.awt.Color(105, 105, 105));
        JLabel14.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        JLabel14.setForeground(new java.awt.Color(1, 1, 1));
        JLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-24x24.png"))); // NOI18N
        JLabel14.setText("USER ID");
        Panel2.add(JLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel43.setBackground(new java.awt.Color(105, 105, 105));
        jLabel43.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(1, 1, 1));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel43.setText("OLD PASSWORD");
        Panel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel49.setBackground(new java.awt.Color(105, 105, 105));
        jLabel49.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(1, 1, 1));
        jLabel49.setText("ACTION");
        Panel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jLabel50.setBackground(new java.awt.Color(254, 254, 254));
        jLabel50.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(1, 1, 1));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-orange-24x24.png"))); // NOI18N
        jLabel50.setText("SAVE");
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel50.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel50.setOpaque(true);
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        Panel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 170, 35));

        jLabel51.setBackground(new java.awt.Color(254, 254, 254));
        jLabel51.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(1, 1, 1));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/status-24x24.png"))); // NOI18N
        jLabel51.setText("RESET");
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel51.setOpaque(true);
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        Panel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 170, 35));

        JSeparator37.setForeground(new java.awt.Color(1, 1, 1));
        Panel2.add(JSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, -1));

        JSeparator39.setForeground(new java.awt.Color(1, 1, 1));
        Panel2.add(JSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, -1));

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));

        jLabel52.setBackground(new java.awt.Color(105, 105, 105));
        jLabel52.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(1, 1, 1));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel52.setText("USER DATE CREATION");
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel53.setBackground(new java.awt.Color(105, 105, 105));
        jLabel53.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(1, 1, 1));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel53.setText("USER LAST EDIT ON");
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JField44.setBackground(new java.awt.Color(254, 254, 254));
        JField44.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField44.setForeground(new java.awt.Color(1, 1, 1));
        JField44.setText("- LocalDateNow");
        JField44.setBorder(null);
        JField44.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField44.setEnabled(false);

        JField45.setBackground(new java.awt.Color(254, 254, 254));
        JField45.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField45.setForeground(new java.awt.Color(1, 1, 1));
        JField45.setText("- LocalDateNow");
        JField45.setBorder(null);
        JField45.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField45.setEnabled(false);

        JField46.setBackground(new java.awt.Color(254, 254, 254));
        JField46.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField46.setForeground(new java.awt.Color(1, 1, 1));
        JField46.setText("- LocalDateNow");
        JField46.setBorder(null);
        JField46.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField46.setEnabled(false);

        jLabel54.setBackground(new java.awt.Color(105, 105, 105));
        jLabel54.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(1, 1, 1));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel54.setText("USER ROLE");
        jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JField46, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JField45, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JField44, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel52)
                .addGap(0, 0, 0)
                .addComponent(JField44, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addGap(0, 0, 0)
                .addComponent(JField45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54)
                .addGap(0, 0, 0)
                .addComponent(JField46, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        Panel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 360, 390));

        JSeparator40.setForeground(new java.awt.Color(1, 1, 1));
        Panel2.add(JSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 170, 10));

        JSeparator41.setForeground(new java.awt.Color(1, 1, 1));
        Panel2.add(JSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 170, 10));

        UserProfilePanel1.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        UserProfilePanel1.setForeground(new java.awt.Color(80, 80, 80));
        UserProfilePanel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserProfilePanel1.setText("UserProfilePanel @Version x.x Built On xx xx xxxx");
        UserProfilePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel2.add(UserProfilePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 628, 310, 30));

        jLabel56.setBackground(new java.awt.Color(105, 105, 105));
        jLabel56.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(1, 1, 1));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel56.setText("NEW PASSWORD");
        Panel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        JField48.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField48.setForeground(new java.awt.Color(1, 1, 1));
        JField48.setText("Please enter new password");
        JField48.setBorder(null);
        JField48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField48.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel2.add(JField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 35));

        JSeparator43.setForeground(new java.awt.Color(1, 1, 1));
        Panel2.add(JSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 300, -1));

        jLabel57.setBackground(new java.awt.Color(105, 105, 105));
        jLabel57.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(1, 1, 1));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel57.setText("CONFIRM PASSWORD");
        Panel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        JField49.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField49.setForeground(new java.awt.Color(1, 1, 1));
        JField49.setText("Please re-enter your new password");
        JField49.setBorder(null);
        JField49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField49.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel2.add(JField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 35));

        JSeparator44.setForeground(new java.awt.Color(1, 1, 1));
        Panel2.add(JSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, -1));

        MainTabbedPanel.addTab("Password", Panel2);

        Panel3.setPreferredSize(new java.awt.Dimension(1050, 570));
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JField38.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField38.setForeground(new java.awt.Color(1, 1, 1));
        JField38.setText("Please enter your old security phrase");
        JField38.setBorder(null);
        JField38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField38.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel3.add(JField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 35));

        JField47.setBackground(new java.awt.Color(242, 242, 242));
        JField47.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField47.setForeground(new java.awt.Color(1, 1, 1));
        JField47.setText("User ID");
        JField47.setBorder(null);
        JField47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField47.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField47.setEnabled(false);
        Panel3.add(JField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 35));

        menuBtn22.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn22.setText("CHANGE SECURITY PHRASE");
        menuBtn22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn22.setOpaque(true);
        Panel3.add(menuBtn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 620, 40));

        menuBtn23.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn23.setText("ACCOUNT INFORMATION");
        menuBtn23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn23.setOpaque(true);
        Panel3.add(menuBtn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 360, 40));

        JLabel15.setBackground(new java.awt.Color(105, 105, 105));
        JLabel15.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        JLabel15.setForeground(new java.awt.Color(1, 1, 1));
        JLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-24x24.png"))); // NOI18N
        JLabel15.setText("USER ID");
        Panel3.add(JLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel45.setBackground(new java.awt.Color(105, 105, 105));
        jLabel45.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(1, 1, 1));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel45.setText("OLD SECURITY PHRASE");
        Panel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel55.setBackground(new java.awt.Color(105, 105, 105));
        jLabel55.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(1, 1, 1));
        jLabel55.setText("ACTION");
        Panel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jLabel58.setBackground(new java.awt.Color(254, 254, 254));
        jLabel58.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(1, 1, 1));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-orange-24x24.png"))); // NOI18N
        jLabel58.setText("SAVE");
        jLabel58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel58.setOpaque(true);
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        Panel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 170, 35));

        jLabel59.setBackground(new java.awt.Color(254, 254, 254));
        jLabel59.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(1, 1, 1));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/status-24x24.png"))); // NOI18N
        jLabel59.setText("RESET");
        jLabel59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel59.setOpaque(true);
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        Panel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 170, 35));

        JSeparator38.setForeground(new java.awt.Color(1, 1, 1));
        Panel3.add(JSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, -1));

        JSeparator42.setForeground(new java.awt.Color(1, 1, 1));
        Panel3.add(JSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, -1));

        jPanel11.setBackground(new java.awt.Color(254, 254, 254));

        jLabel60.setBackground(new java.awt.Color(105, 105, 105));
        jLabel60.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(1, 1, 1));
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel60.setText("USER DATE CREATION");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel61.setBackground(new java.awt.Color(105, 105, 105));
        jLabel61.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(1, 1, 1));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel61.setText("USER LAST EDIT ON");
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JField50.setBackground(new java.awt.Color(254, 254, 254));
        JField50.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField50.setForeground(new java.awt.Color(1, 1, 1));
        JField50.setText("- LocalDateNow");
        JField50.setBorder(null);
        JField50.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField50.setEnabled(false);

        JField51.setBackground(new java.awt.Color(254, 254, 254));
        JField51.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField51.setForeground(new java.awt.Color(1, 1, 1));
        JField51.setText("- LocalDateNow");
        JField51.setBorder(null);
        JField51.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField51.setEnabled(false);

        JField52.setBackground(new java.awt.Color(254, 254, 254));
        JField52.setFont(new java.awt.Font("Alibaba PuHuiTi R", 1, 12)); // NOI18N
        JField52.setForeground(new java.awt.Color(1, 1, 1));
        JField52.setText("- LocalDateNow");
        JField52.setBorder(null);
        JField52.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        JField52.setEnabled(false);

        jLabel62.setBackground(new java.awt.Color(105, 105, 105));
        jLabel62.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(1, 1, 1));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-24x24.png"))); // NOI18N
        jLabel62.setText("USER ROLE");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JField52, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JField51, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JField50, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel60)
                .addGap(0, 0, 0)
                .addComponent(JField50, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel61)
                .addGap(0, 0, 0)
                .addComponent(JField51, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel62)
                .addGap(0, 0, 0)
                .addComponent(JField52, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        Panel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 360, 390));

        JSeparator45.setForeground(new java.awt.Color(1, 1, 1));
        Panel3.add(JSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 170, 10));

        JSeparator46.setForeground(new java.awt.Color(1, 1, 1));
        Panel3.add(JSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 170, 10));

        UserProfilePanel2.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        UserProfilePanel2.setForeground(new java.awt.Color(80, 80, 80));
        UserProfilePanel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserProfilePanel2.setText("UserProfilePanel @Version x.x Built On xx xx xxxx");
        UserProfilePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel3.add(UserProfilePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 628, 310, 30));

        jLabel63.setBackground(new java.awt.Color(105, 105, 105));
        jLabel63.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(1, 1, 1));
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel63.setText("NEW SECURITY PHRASE");
        Panel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        JField53.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField53.setForeground(new java.awt.Color(1, 1, 1));
        JField53.setText("Please enter new security phrase");
        JField53.setBorder(null);
        JField53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField53.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel3.add(JField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 35));

        JSeparator47.setForeground(new java.awt.Color(1, 1, 1));
        Panel3.add(JSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 300, -1));

        jLabel64.setBackground(new java.awt.Color(105, 105, 105));
        jLabel64.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(1, 1, 1));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordKey-24x24.png"))); // NOI18N
        jLabel64.setText("CONFIRM SECURITY PHRASE");
        Panel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        JField54.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        JField54.setForeground(new java.awt.Color(1, 1, 1));
        JField54.setText("Please re-enter your new security phrase");
        JField54.setBorder(null);
        JField54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JField54.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        Panel3.add(JField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 35));

        JSeparator48.setForeground(new java.awt.Color(1, 1, 1));
        Panel3.add(JSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, -1));

        MainTabbedPanel.addTab("Security Phrase", Panel3);

        getContentPane().add(MainTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillInUserDetials(){
        
        UserAuthentication userAuthentication = UserAccountController.getAuthenticationUserDetails();
        UserAccount user = UserAccountController.getUserDetailsByUserId(userAuthentication.getUserId());
        
        UserRoleType userRole = userAuthentication.getUserRoleType();
        String createdDate = DateTimeUtils.formatStrDateTime(user.getCreatedAt());
        String updatedDate = DateTimeUtils.formatStrDateTime(user.getUpdatedAt());
        
        JField36.setText(String.valueOf(user.getUserId()));
        JField43.setText(String.valueOf(user.getUserId()));
        JField47.setText(String.valueOf(user.getUserId()));
        JField28.setText(user.getUsername());
        JField29.setText(user.getFirstName());
        JField30.setText(user.getLastName());
        JField31.setText("******");
        JField34.setText("******");
        JField41.setText(user.getEmail());
        
        JField39.setText("- " + createdDate);
        JField40.setText("- " + updatedDate);
        JField42.setText("- " + userRole);
        
        JField44.setText("- " + createdDate);
        JField45.setText("- " + updatedDate);
        JField46.setText("- " + userRole);
        
        JField50.setText("- " + createdDate);
        JField51.setText("- " + updatedDate);
        JField52.setText("- " + userRole);
    }
    
    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        fillInUserDetials();
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
       if (updateUserProfileById(Integer.parseInt(JField36.getText()),JField28.getText(),JField29.getText(),JField30.getText(),JField41.getText())) {
           fillInUserDetials();
       }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        if (changePasswordById(Integer.parseInt(JField36.getText()),JField37.getText(),JField48.getText(),JField49.getText())) {
            JField37.setText("Please enter your old password");
            JField48.setText("Please enter new password");
            JField49.setText("Please re-enter your new password");
            fillInUserDetials();
        }
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        JField37.setText("Please enter your old password");
        JField48.setText("Please enter new password");
        JField49.setText("Please re-enter your new password");
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        if (changeSecurityPhraseById(Integer.parseInt(JField36.getText()),JField38.getText(),JField53.getText(),JField54.getText())) {
            JField38.setText("Please enter your old security phrase");
            JField53.setText("Please enter new security phrase");
            JField54.setText("Please re-enter your new security phrase");
            fillInUserDetials();
        }
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        JField38.setText("Please enter your old security phrase");
        JField53.setText("Please enter new security phrase");
        JField54.setText("Please re-enter your new security phrase");
    }//GEN-LAST:event_jLabel59MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JField28;
    private javax.swing.JTextField JField29;
    private javax.swing.JTextField JField30;
    private javax.swing.JTextField JField31;
    private javax.swing.JTextField JField34;
    private javax.swing.JTextField JField36;
    private javax.swing.JTextField JField37;
    private javax.swing.JTextField JField38;
    private javax.swing.JTextField JField39;
    private javax.swing.JTextField JField40;
    private javax.swing.JTextField JField41;
    private javax.swing.JTextField JField42;
    private javax.swing.JTextField JField43;
    private javax.swing.JTextField JField44;
    private javax.swing.JTextField JField45;
    private javax.swing.JTextField JField46;
    private javax.swing.JTextField JField47;
    private javax.swing.JTextField JField48;
    private javax.swing.JTextField JField49;
    private javax.swing.JTextField JField50;
    private javax.swing.JTextField JField51;
    private javax.swing.JTextField JField52;
    private javax.swing.JTextField JField53;
    private javax.swing.JTextField JField54;
    private javax.swing.JLabel JLabel13;
    private javax.swing.JLabel JLabel14;
    private javax.swing.JLabel JLabel15;
    private javax.swing.JSeparator JSeparator25;
    private javax.swing.JSeparator JSeparator26;
    private javax.swing.JSeparator JSeparator27;
    private javax.swing.JSeparator JSeparator28;
    private javax.swing.JSeparator JSeparator30;
    private javax.swing.JSeparator JSeparator33;
    private javax.swing.JSeparator JSeparator34;
    private javax.swing.JSeparator JSeparator35;
    private javax.swing.JSeparator JSeparator36;
    private javax.swing.JSeparator JSeparator37;
    private javax.swing.JSeparator JSeparator38;
    private javax.swing.JSeparator JSeparator39;
    private javax.swing.JSeparator JSeparator40;
    private javax.swing.JSeparator JSeparator41;
    private javax.swing.JSeparator JSeparator42;
    private javax.swing.JSeparator JSeparator43;
    private javax.swing.JSeparator JSeparator44;
    private javax.swing.JSeparator JSeparator45;
    private javax.swing.JSeparator JSeparator46;
    private javax.swing.JSeparator JSeparator47;
    private javax.swing.JSeparator JSeparator48;
    private javax.swing.JTabbedPane MainTabbedPanel;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JLabel UserProfilePanel;
    private javax.swing.JLabel UserProfilePanel1;
    private javax.swing.JLabel UserProfilePanel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel menuBtn18;
    private javax.swing.JLabel menuBtn19;
    private javax.swing.JLabel menuBtn20;
    private javax.swing.JLabel menuBtn21;
    private javax.swing.JLabel menuBtn22;
    private javax.swing.JLabel menuBtn23;
    // End of variables declaration//GEN-END:variables
}
