/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.project.ui.project_manager;

import com.project.controller.ProjectModuleController;
import com.project.ui.administrator.*;
import java.util.Map;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author chanh
 */
public class ProjectManagerDashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminDashboard
     */
    public ProjectManagerDashboard() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);        
        // adminPanelVersionLabel.setText(PropertiesReader.getProperty("AdminDashboardVersion"));
        dashboardRefresh();
    }
    
    public static void dashboardRefresh(){
        Map<String, Integer> moduleStatus = ProjectModuleController.getModuleStatusForPM();
        //Module Status
        menuBtn22.setText(String.valueOf(moduleStatus.get("total")));
        menuBtn28.setText(String.valueOf(moduleStatus.get("active")));
        menuBtn26.setText(String.valueOf(moduleStatus.get("unassigned")));
        menuBtn34.setText(String.valueOf(moduleStatus.get("completed")));
        menuBtn36.setText(String.valueOf(moduleStatus.get("upcoming")));
        // First Marker and Second Marker
        menuBtn15.setText(String.valueOf(moduleStatus.get("firstMarker")));
        menuBtn14.setText(String.valueOf(moduleStatus.get("secondMarker")));
        
        Map<String, Integer> reportStatus = ProjectModuleController.getReportStatusForPM();
        menuBtn24.setText(String.valueOf(reportStatus.get("total")));
        menuBtn30.setText(String.valueOf(reportStatus.get("pendingSubmit")));
        menuBtn32.setText(String.valueOf(reportStatus.get("pendingMarking")));
        menuBtn38.setText(String.valueOf(reportStatus.get("marked")));
        menuBtn40.setText(String.valueOf(reportStatus.get("overdue")));
        // menuBtn13.setText(String.valueOf(UserAccountOperator.checkTotalActiveSalesPerson()));
        // menuBtn15.setText(String.valueOf(checkTotalFurniture()));
        // menuBtn14.setText(String.valueOf(checkStockAlertsFurniture()));
        // menuBtn16.setText(String.valueOf(SalesOperator.getTotalSalesAmount()));
        // menuBtn17.setText(String.valueOf(SalesOperator.getTotalPendingSales()));
        // menuBtn18.setText(String.valueOf(SalesOperator.getTotalSuccessfulSales()));
        // menuBtn19.setText(String.valueOf(SalesOperator.getTotalCancelledSales()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        menuBtn9 = new javax.swing.JLabel();
        menuBtn10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        menuBtn2 = new javax.swing.JLabel();
        menuBtn14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        menuBtn1 = new javax.swing.JLabel();
        menuBtn15 = new javax.swing.JLabel();
        menuBtn20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        menuBtn21 = new javax.swing.JLabel();
        menuBtn22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        menuBtn27 = new javax.swing.JLabel();
        menuBtn28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        menuBtn25 = new javax.swing.JLabel();
        menuBtn26 = new javax.swing.JLabel();
        adminPanelVersionLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        menuBtn33 = new javax.swing.JLabel();
        menuBtn34 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        menuBtn35 = new javax.swing.JLabel();
        menuBtn36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        menuBtn23 = new javax.swing.JLabel();
        menuBtn24 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        menuBtn29 = new javax.swing.JLabel();
        menuBtn30 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        menuBtn31 = new javax.swing.JLabel();
        menuBtn32 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        menuBtn37 = new javax.swing.JLabel();
        menuBtn38 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        menuBtn39 = new javax.swing.JLabel();
        menuBtn40 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBtn9.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn9.setText("Student Feedback");
        menuBtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn9.setOpaque(true);
        MainPanel.add(menuBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 1020, 40));

        menuBtn10.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn10.setText("LECTURER DETAILS");
        menuBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn10.setOpaque(true);
        MainPanel.add(menuBtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 500, 40));

        jPanel7.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn2.setBackground(new java.awt.Color(250, 250, 250));
        menuBtn2.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn2.setText("Second Markers");
        menuBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn2.setOpaque(true);

        menuBtn14.setBackground(new java.awt.Color(254, 254, 254));
        menuBtn14.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn14.setText("0");
        menuBtn14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn14.setOpaque(true);
        menuBtn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(menuBtn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(menuBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuBtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 240, -1));

        jPanel8.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn1.setBackground(new java.awt.Color(250, 250, 250));
        menuBtn1.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn1.setText("Supervisor");
        menuBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn1.setOpaque(true);

        menuBtn15.setBackground(new java.awt.Color(254, 254, 254));
        menuBtn15.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn15.setText("0");
        menuBtn15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn15.setOpaque(true);
        menuBtn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(menuBtn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(menuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 240, 120));

        menuBtn20.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuBtn20.setText("MODULES");
        menuBtn20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn20.setOpaque(true);
        MainPanel.add(menuBtn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1020, 40));

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn21.setBackground(new java.awt.Color(250, 250, 250));
        menuBtn21.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn21.setText("Total Modules");
        menuBtn21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn21.setOpaque(true);

        menuBtn22.setBackground(new java.awt.Color(254, 254, 254));
        menuBtn22.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn22.setText("0");
        menuBtn22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn22.setOpaque(true);
        menuBtn22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn21, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(menuBtn21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 120));

        jPanel12.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn27.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn27.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn27.setText("Unassigned Modules");
        menuBtn27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn27.setOpaque(true);
        menuBtn27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn27MouseClicked(evt);
            }
        });

        menuBtn28.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn28.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn28.setText("0");
        menuBtn28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn28.setOpaque(true);
        menuBtn28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn27, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(menuBtn27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 180, -1));

        jPanel11.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn25.setBackground(new java.awt.Color(204, 255, 204));
        menuBtn25.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn25.setText("Active Modules");
        menuBtn25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn25.setOpaque(true);

        menuBtn26.setBackground(new java.awt.Color(204, 255, 204));
        menuBtn26.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn26.setText("0");
        menuBtn26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn26.setOpaque(true);
        menuBtn26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn25, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(menuBtn25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 180, 120));

        adminPanelVersionLabel.setFont(new java.awt.Font("Alibaba PuHuiTi R", 0, 12)); // NOI18N
        adminPanelVersionLabel.setForeground(new java.awt.Color(80, 80, 80));
        adminPanelVersionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adminPanelVersionLabel.setText("AdminPanel @Version x.x Built On xx xx xxxx");
        adminPanelVersionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.add(adminPanelVersionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 628, 620, 30));

        jPanel15.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn33.setBackground(new java.awt.Color(153, 255, 153));
        menuBtn33.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn33.setText("Completed Modules");
        menuBtn33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn33.setOpaque(true);

        menuBtn34.setBackground(new java.awt.Color(153, 255, 153));
        menuBtn34.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn34.setText("0");
        menuBtn34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn34.setOpaque(true);
        menuBtn34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn34MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn33, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(menuBtn33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 180, 120));

        jPanel16.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn35.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn35.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn35.setText("Upcoming Modules");
        menuBtn35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn35.setOpaque(true);

        menuBtn36.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn36.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn36.setText("0");
        menuBtn36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn36.setOpaque(true);
        menuBtn36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn36MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn35, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(menuBtn35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn36, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 180, 120));

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn23.setBackground(new java.awt.Color(250, 250, 250));
        menuBtn23.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn23.setText("Total Report");
        menuBtn23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn23.setOpaque(true);

        menuBtn24.setBackground(new java.awt.Color(254, 254, 254));
        menuBtn24.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn24.setText("0");
        menuBtn24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn24.setOpaque(true);
        menuBtn24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn23, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(menuBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 120));

        jPanel13.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn29.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn29.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn29.setText("Pending Submit");
        menuBtn29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn29.setOpaque(true);
        menuBtn29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn29MouseClicked(evt);
            }
        });

        menuBtn30.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn30.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn30.setText("0");
        menuBtn30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn30.setOpaque(true);
        menuBtn30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn30MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn29, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(menuBtn29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 180, -1));

        jPanel14.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn31.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn31.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn31.setText("Pending Marking");
        menuBtn31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn31.setOpaque(true);

        menuBtn32.setBackground(new java.awt.Color(255, 255, 153));
        menuBtn32.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn32.setText("0");
        menuBtn32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn32.setOpaque(true);
        menuBtn32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn32MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn31, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(menuBtn31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 180, 120));

        jPanel17.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn37.setBackground(new java.awt.Color(255, 102, 102));
        menuBtn37.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn37.setForeground(new java.awt.Color(255, 255, 255));
        menuBtn37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn37.setText("Overdue");
        menuBtn37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn37.setOpaque(true);

        menuBtn38.setBackground(new java.awt.Color(255, 102, 102));
        menuBtn38.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn38.setForeground(new java.awt.Color(255, 255, 255));
        menuBtn38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn38.setText("0");
        menuBtn38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn38.setOpaque(true);
        menuBtn38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn38MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn37, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(menuBtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 180, 120));

        jPanel18.setBackground(new java.awt.Color(254, 254, 254));

        menuBtn39.setBackground(new java.awt.Color(153, 255, 153));
        menuBtn39.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 14)); // NOI18N
        menuBtn39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn39.setText("Marked");
        menuBtn39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBtn39.setOpaque(true);

        menuBtn40.setBackground(new java.awt.Color(153, 255, 153));
        menuBtn40.setFont(new java.awt.Font("Alibaba PuHuiTi M", 0, 18)); // NOI18N
        menuBtn40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn40.setText("0");
        menuBtn40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn40.setOpaque(true);
        menuBtn40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn40MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn39, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuBtn40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(menuBtn39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuBtn40, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 180, 120));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtn14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn14MouseClicked
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn14MouseClicked

    private void menuBtn15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn15MouseClicked
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn15MouseClicked

    private void menuBtn27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn27MouseClicked

    private void menuBtn29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtn29MouseClicked

    private void menuBtn22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn22MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn22MouseClicked

    private void menuBtn28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn28MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn28MouseClicked

    private void menuBtn36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn36MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn36MouseClicked

    private void menuBtn26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn26MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn26MouseClicked

    private void menuBtn34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn34MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn4");
    }//GEN-LAST:event_menuBtn34MouseClicked

    private void menuBtn24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn24MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn3");
    }//GEN-LAST:event_menuBtn24MouseClicked

    private void menuBtn30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn30MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn3");
    }//GEN-LAST:event_menuBtn30MouseClicked

    private void menuBtn32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn32MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn3");
    }//GEN-LAST:event_menuBtn32MouseClicked

    private void menuBtn40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn40MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn3");
    }//GEN-LAST:event_menuBtn40MouseClicked

    private void menuBtn38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn38MouseClicked
        // TODO add your handling code here:
        this.dispose();
        ProjectManagerGui.ButtonClicked("menuBtn3");
    }//GEN-LAST:event_menuBtn38MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel adminPanelVersionLabel;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel menuBtn1;
    private javax.swing.JLabel menuBtn10;
    private static javax.swing.JLabel menuBtn14;
    private static javax.swing.JLabel menuBtn15;
    private javax.swing.JLabel menuBtn2;
    private javax.swing.JLabel menuBtn20;
    private javax.swing.JLabel menuBtn21;
    private static javax.swing.JLabel menuBtn22;
    private javax.swing.JLabel menuBtn23;
    private static javax.swing.JLabel menuBtn24;
    private javax.swing.JLabel menuBtn25;
    private static javax.swing.JLabel menuBtn26;
    private javax.swing.JLabel menuBtn27;
    private static javax.swing.JLabel menuBtn28;
    private javax.swing.JLabel menuBtn29;
    private static javax.swing.JLabel menuBtn30;
    private javax.swing.JLabel menuBtn31;
    private static javax.swing.JLabel menuBtn32;
    private javax.swing.JLabel menuBtn33;
    private static javax.swing.JLabel menuBtn34;
    private javax.swing.JLabel menuBtn35;
    private static javax.swing.JLabel menuBtn36;
    private javax.swing.JLabel menuBtn37;
    private static javax.swing.JLabel menuBtn38;
    private javax.swing.JLabel menuBtn39;
    private static javax.swing.JLabel menuBtn40;
    private javax.swing.JLabel menuBtn9;
    // End of variables declaration//GEN-END:variables
}
